spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/ledgerly
    username: admin
    password: admin

  jpa:
    hibernate:
          ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration