-- =========================================
-- USERS
-- =========================================

INSERT INTO users (id,
                   first_name,
                   last_name,
                   email,
                   password,
                   default_currency,
                   timezone,
                   created_at,
                   updated_at)
VALUES (1,
        'Julio',
        'Hernandez',
        'julio@test.com',
        '$2b$12$jqZPNd96xUTqPhe6daLSp.dIxJBANAb3R/tDVmUb24yTzPLaLSIzK',
        'EUR',
        'Europe/Rome',
        NOW(),
        NOW());

-- =========================================
-- CATEGORIES
-- =========================================

INSERT INTO categories (id,
                        user_id,
                        name,
                        description,
                        color,
                        active,
                        created_at,
                        updated_at)
VALUES (1,
        1,
        'Salary',
        'Monthly salary income',
        '#4CAF50',
        true,
        NOW(),
        NOW()),
       (2,
        1,
        'Food',
        'Groceries and restaurants',
        '#FF9800',
        true,
        NOW(),
        NOW()),
       (3,
        1,
        'Rent',
        'Monthly apartment rent',
        '#F44336',
        true,
        NOW(),
        NOW()),
       (4,
        1,
        'Transport',
        'Public transportation and mobility',
        '#2196F3',
        true,
        NOW(),
        NOW()),
       (5,
        1,
        'Entertainment',
        'Movies, events and hobbies',
        '#9C27B0',
        true,
        NOW(),
        NOW());

-- =========================================
-- TRANSACTIONS
-- =========================================

INSERT INTO transactions (id,
                          user_id,
                          category_id,
                          type,
                          amount,
                          description,
                          transaction_date,
                          created_at,
                          updated_at)
VALUES (1,
        1,
        1,
        'INCOME',
        3200.00,
        'Monthly salary',
        CURRENT_DATE,
        NOW(),
        NOW()),
       (2,
        1,
        2,
        'EXPENSE',
        85.50,
        'Groceries supermarket',
        CURRENT_DATE,
        NOW(),
        NOW()),
       (3,
        1,
        3,
        'EXPENSE',
        950.00,
        'Apartment rent',
        CURRENT_DATE,
        NOW(),
        NOW()),
       (4,
        1,
        4,
        'EXPENSE',
        35.00,
        'Metro monthly card',
        CURRENT_DATE,
        NOW(),
        NOW()),
       (5,
        1,
        5,
        'EXPENSE',
        60.00,
        'Cinema and dinner',
        CURRENT_DATE,
        NOW(),
        NOW());

-- =========================================
-- BUDGETS
-- =========================================

INSERT INTO budgets (id,
                     category_id,
                     user_id,
                     amount_limit,
                     month,
                     year,
                     created_at,
                     updated_at)
VALUES (1,
        2,
        1,
        400.00,
        5,
        2026,
        NOW(),
        NOW()),
       (2,
        4,
        1,
        100.00,
        5,
        2026,
        NOW(),
        NOW()),
       (3,
        5,
        1,
        250.00,
        5,
        2026,
        NOW(),
        NOW());